/* FIle: 0.2 - Config table & report table*/
 

IF OBJECT_ID ( 'dbo.ConfigSet' ) IS NOT NULL   
    DROP PROCEDURE dbo.ConfigSet;  
GO  
CREATE PROCEDURE dbo.ConfigSet 
    @MSN_IN INTEGER, 
    @STANDARD_IN VARCHAR(10), 
    @V_ICAO VARCHAR(10), 
    @V_RANK_IN INTEGER,
    @V_JAGUAR_CACODE VARCHAR(20)
WITH EXECUTE AS CALLER 
AS  
  /* Get the table ready to collect selected ADAPCINUMBER rows */

DROP TABLE IF EXISTS CONFIG;
CREATE TABLE CONFIG(
    MSN INTEGER,
    STANDARD VARCHAR(5),
    VERSION_ICAO VARCHAR(8),
    VERSION_RANK INTEGER,
    JAGUAR_CACODE VARCHAR(20),
    CICO_CACODE VARCHAR(8)
);

IF (@MSN_IN>0)
    INSERT INTO CONFIG VALUES(@MSN_IN,@STANDARD_IN,@V_ICAO, @V_RANK_IN, @V_JAGUAR_CACODE,'-')
/*ELSE
    INSERT INTO CONFIG VALUES(10140,'ST2','DAL01',114,'DK-S18/19','-')*/

UPDATE CONFIG 
    SET CONFIG.CICO_CACODE = JAGUAR_MAP.CICO_CACODE 
    FROM CONFIG JOIN JAGUAR_MAP ON CONFIG.JAGUAR_CACODE=JAGUAR_MAP.JAGUAR_CACODE 
    Where JAGUAR_MAP.JAGUAR_CACODE=CONFIG.JAGUAR_CACODE;


GO  
/*dbo.ConfigSet 10140, 'ST2', 'DAL01', 114, 'DK-S18/19'*/
/*dbo.ConfigSet 10142, 'ST5', 'EZY04', 41, 'DK-S18/19'*/
/*dbo.ConfigSet 10142, 'ST5', 'EZY04', 41, 'DK-S18/19'*/

/*dbo.ConfigSet 10411, 'ST5', 'APJ02', 5, 'DK-S18/19'*/
/*dbo.ConfigSet 10911, 'ST8', 'SBI04', 1, 'DK-S18/19'*/
/*dbo.ConfigSet 10174, 'ST8', 'MEA03', 7, 'DK-S18/19'*/
dbo.ConfigSet 10101, 'ST8', 'J3K06', 1, 'DK-Cone_HAM'


/*DK-Cone_HAM*/

SELECT * FROM CONFIG;
