DROP TABLE IF EXISTS A_IXOFFEFF;

declare @V_MAX_STRING INTEGER = CAST((SELECT max(len(RANGE)) AS Max_Length_String FROM [dbo].[A_IXOFFEFF_TEMP])AS INT)

CREATE TABLE A_IXOFFEFF(
	LONUMBER VARCHAR(18),
	LOLEGACYNUMBER VARCHAR(10),
	EFFTYPE VARCHAR(12),
	STDCODE VARCHAR(5),
	VERSIONCODE VARCHAR(8),
	INDUSSTDCODE VARCHAR(10),
	CDATE VARCHAR(20),
	UDATE VARCHAR(20),
	LOTYPE VARCHAR(10),
	COCODE VARCHAR(10),
	RANGE VARCHAR(12),
	RANGE_START INTEGER,
	RANGE_END INTEGER
)

DROP TABLE IF EXISTS A_IXOFFEFF_SPLIT_TEMP;
CREATE TABLE A_IXOFFEFF_SPLIT_TEMP(
	LONUMBER VARCHAR(18),
	LOLEGACYNUMBER VARCHAR(10),
	EFFTYPE VARCHAR(12),
	STDCODE VARCHAR(5),
	VERSIONCODE VARCHAR(8),
	INDUSSTDCODE VARCHAR(10),
	CDATE VARCHAR(20),
	UDATE VARCHAR(20),
	LOTYPE VARCHAR(10),
	COCODE VARCHAR(10),
	RANGE VARCHAR(12)
)



DECLARE @PLONUMBER VARCHAR(18)
DECLARE @PLOLEGACYNUMBER VARCHAR(10)
DECLARE @PEFFTYPE VARCHAR(12)
DECLARE @PSTDCODE VARCHAR(5)
DECLARE @PVERSIONCODE VARCHAR(8)
DECLARE @PINDUSSTDCODE VARCHAR(10)
DECLARE @PCDATE VARCHAR(20)
DECLARE @PUDATE VARCHAR(20)
DECLARE @PLOTYPE VARCHAR(10)
DECLARE @PCOCODE VARCHAR(10)
DECLARE @PRANGE NVARCHAR(max)


DECLARE SPLIT_RANGE CURSOR LOCAL FAST_FORWARD FOR 
        SELECT
                LONUMBER, LOLEGACYNUMBER, EFFTYPE, STDCODE, VERSIONCODE, INDUSSTDCODE, CDATE, UDATE, LOTYPE, COCODE, RANGE
        FROM [dbo].[A_IXOFFEFF_TEMP]

OPEN SPLIT_RANGE
FETCH NEXT FROM SPLIT_RANGE 
INTO @PLONUMBER, @PLOLEGACYNUMBER, @PEFFTYPE, @PSTDCODE, @PVERSIONCODE, @PINDUSSTDCODE, @PCDATE, @PUDATE, @PLOTYPE, @PCOCODE, @PRANGE

 
WHILE @@FETCH_STATUS = 0
BEGIN

    INSERT INTO A_IXOFFEFF_SPLIT_TEMP
            SELECT @PLONUMBER, @PLOLEGACYNUMBER, @PEFFTYPE, @PSTDCODE, @PVERSIONCODE, @PINDUSSTDCODE, @PCDATE, @PUDATE, @PLOTYPE, @PCOCODE,
                    SPL.value FROM STRING_SPLIT(@PRANGE,',') AS SPL
    
            		FETCH NEXT FROM SPLIT_RANGE 
            		INTO 
                    @PLONUMBER, @PLOLEGACYNUMBER, @PEFFTYPE, @PSTDCODE, @PVERSIONCODE, @PINDUSSTDCODE, @PCDATE, @PUDATE, @PLOTYPE, @PCOCODE, @PRANGE
END 


INSERT INTO A_IXOFFEFF
        SELECT 
         LONUMBER, LOLEGACYNUMBER, EFFTYPE, STDCODE, VERSIONCODE, INDUSSTDCODE, CDATE, UDATE, LOTYPE, COCODE, 
		 RANGE,
         CAST(SUBSTRING(RANGE, 1, CHARINDEX('-', RANGE) - 1) as INT) as RSTART,
         CAST(REVERSE( LEFT( REVERSE(RANGE), CHARINDEX('-', REVERSE(RANGE))-1 ) ) AS INT) as REND
         From A_IXOFFEFF_SPLIT_TEMP WHERE RANGE like '%-%'

INSERT INTO A_IXOFFEFF
        SELECT
         LONUMBER, LOLEGACYNUMBER, EFFTYPE, STDCODE, VERSIONCODE, INDUSSTDCODE, CDATE, UDATE, LOTYPE, COCODE,  
         RANGE, CAST(RANGE as INT), 0
         From A_IXOFFEFF_SPLIT_TEMP WHERE RANGE not like '%-%'

DROP TABLE A_IXOFFEFF_SPLIT_TEMP;
drop table A_IXOFFEFF_TEMP;

SELECT * from A_IXOFFEFF;


