IF OBJECT_ID ( 'dbo.ClearSelections' ) IS NOT NULL   
    DROP PROCEDURE dbo.ClearSelections;  
GO  
CREATE PROCEDURE dbo.ClearSelections
WITH EXECUTE AS CALLER  
AS  
    DROP TABLE IF EXISTS SELECTION_REPORT;

    DROP TABLE IF EXISTS SELECTED_ADAPCINUMBER;
    DROP TABLE IF EXISTS SELECTED_CINS;
    DROP TABLE IF EXISTS SELECTED_CINS_ADAPCI;
    DROP TABLE IF EXISTS SELECTED_CIN_ADAPLONUMBER;

    DROP TABLE IF EXISTS SELECTED_LO_STANDARD;
    DROP TABLE IF EXISTS SELECTED_LO_VERSION;
    DROP TABLE IF EXISTS SELECTED_LONUMBER_EFF;

    DROP TABLE IF EXISTS SELECTED_FILTERED_LONUMBER;

    DROP TABLE IF EXISTS SELECTED_ADAPDS;
    DROP TABLE IF EXISTS SELECTED_DRAWINGSET;
    DROP TABLE IF EXISTS SELECTED_DRAWINGS;
    
    DROP TABLE IF EXISTS SELECTED_ADAPDS_DASSY;
    DROP TABLE IF EXISTS SELECTED_O_DASSY
GO

dbo.ClearSelections