/* --------------- STEP 1B ----------------- */
/* Select the CIN, standard selection, options selections */


IF OBJECT_ID ( 'dbo.Step1B' ) IS NOT NULL   
    DROP PROCEDURE dbo.Step1B;  
GO  
CREATE PROCEDURE dbo.Step1B  
WITH EXECUTE AS CALLER  
AS  

/* JAGUAR */
/* Select the CIN, standard selection*/

declare @V_MSN INTEGER = (SELECT TOP 1 MSN FROM CONFIG);
DECLARE @V_STDCODE VARCHAR(5) = (SELECT TOP 1 STANDARD FROM CONFIG);
DECLARE @V_VALIDITY VARCHAR(8) ='STANDARD'

SELECT CIN, RANGE, RANGE_START, RANGE_END, STDCODE INTO #CINS_TEMP
    FROM [dbo].[O_CIN] 
    where VALIDITYTYPE=@V_VALIDITY AND STDCODE=@V_STDCODE
    AND RANGE_START<= @V_MSN AND RANGE_END>=@V_MSN AND RANGE_END<>0;

CREATE TABLE #CINS(CIN VARCHAR(30));

DECLARE @PCIN VARCHAR (30)
DECLARE CINS_CURSOR CURSOR LOCAL FAST_FORWARD FOR 
        SELECT CIN FROM #CINS_TEMP

OPEN CINS_CURSOR
FETCH NEXT FROM CINS_CURSOR 
INTO @PCIN
 
WHILE @@FETCH_STATUS = 0
BEGIN
    INSERT INTO #CINS
        SELECT DISTINCT REPLACE(@PCIN,'/','-') 
        FROM #CINS_TEMP

    FETCH NEXT FROM CINS_CURSOR 
        INTO @PCIN
END

/* Select the CIN, options selection*/

declare @V_VERSIONRANK INTEGER = (SELECT TOP 1 VERSION_RANK FROM CONFIG);
DECLARE @V_VERSION_CODE VARCHAR(10);
SET @V_VERSION_CODE = (SELECT TOP 1 VERSION_ICAO FROM CONFIG);
SET @V_VALIDITY ='VERSION'

SELECT CIN, VALIDITYTYPE, RANGE, RANGE_START, RANGE_END, VERSIONCODE INTO #CINS_TEMP2
    FROM [dbo].[O_CIN] 
    where VALIDITYTYPE=@V_VALIDITY AND VERSIONCODE=@V_VERSION_CODE
    AND RANGE_START<= @V_VERSIONRANK AND RANGE_END>=@V_VERSIONRANK AND RANGE_END<>0;

CREATE TABLE #CINS2(CIN VARCHAR(30));

DECLARE @PCIN2 VARCHAR (30)
DECLARE CINS_CURSOR2 CURSOR LOCAL FAST_FORWARD FOR 
        SELECT CIN FROM #CINS_TEMP2

OPEN CINS_CURSOR2
FETCH NEXT FROM CINS_CURSOR2 
INTO @PCIN2
 
WHILE @@FETCH_STATUS = 0
BEGIN
    INSERT INTO #CINS2
        SELECT DISTINCT REPLACE(@PCIN2,'/','-') 
        FROM #CINS_TEMP2

    FETCH NEXT FROM CINS_CURSOR2
        INTO @PCIN2
END

/* MERGE */
DROP TABLE IF EXISTS SELECTED_CINS;
CREATE TABLE SELECTED_CINS(CIN VARCHAR(30));
INSERT INTO SELECTED_CINS SELECT DISTINCT * from #CINS ORDER BY CIN;
INSERT INTO SELECTED_CINS SELECT DISTINCT * from #CINS2 ORDER BY CIN;


GO  

dbo.Step1B

/* ------------ RESULTS STEP 2&3 --------------*/
SELECT DISTINCT * from SELECTED_CINS;
