/* Step 1.C */

IF OBJECT_ID ( 'dbo.Step1C' ) IS NOT NULL   
    DROP PROCEDURE dbo.Step1C;  
GO  
CREATE PROCEDURE dbo.Step1C
WITH EXECUTE AS CALLER  
AS  
    DROP TABLE IF EXISTS SELECTED_CINS_ADAPCI;
    CREATE TABLE SELECTED_CINS_ADAPCI(ADAPCINUMBER VARCHAR(24), CIN VARCHAR(20));
    
    /* Following tables for tests only */
    DROP TABLE IF EXISTS SELECTED_CINS_ADAPCI1;
    /*DROP TABLE IF EXISTS SELECTED_CINS_ADAPCI2;*/
    CREATE TABLE SELECTED_CINS_ADAPCI1(ADAPCINUMBER VARCHAR(24), CIN VARCHAR(20));
    /*CREATE TABLE SELECTED_CINS_ADAPCI2(ADAPCINUMBER VARCHAR(24), CIN VARCHAR(20));*/

    /* With SELECTED_CINS */
    INSERT INTO SELECTED_CINS_ADAPCI1
        SELECT DISTINCT R_CIN_ADAPCI.ADAPCINUMBER, R_CIN_ADAPCI.CINSTACK 
        FROM R_CIN_ADAPCI 
        JOIN SELECTED_CINS ON SELECTED_CINS.CIN=R_CIN_ADAPCI.CINSTACK
        JOIN SELECTED_ADAPCINUMBER ON SELECTED_ADAPCINUMBER.ADAPCINUMBER=R_CIN_ADAPCI.ADAPCINUMBER

    /* Without SELECTED_CINS */
    /*INSERT INTO SELECTED_CINS_ADAPCI2
        SELECT DISTINCT ADAPCINUMBER, CINSTACK 
        FROM R_CIN_ADAPCI 
        WHERE ADAPCINUMBER IN (SELECT ADAPCINUMBER from SELECTED_ADAPCINUMBER);*/

    /* chosen variant for further processes */
    INSERT INTO SELECTED_CINS_ADAPCI
        Select * from SELECTED_CINS_ADAPCI1;

    DROP TABLE SELECTED_CINS_ADAPCI1;
GO

dbo.Step1C

/*Select * from SELECTED_CINS_ADAPCI1;
Select * from SELECTED_CINS_ADAPCI2;*/
Select * from SELECTED_CINS_ADAPCI;

