IF OBJECT_ID ( 'dbo.Step5' ) IS NOT NULL   
    DROP PROCEDURE dbo.Step5;  
GO  
CREATE PROCEDURE dbo.Step5
WITH EXECUTE AS CALLER  
AS  

    DROP TABLE IF EXISTS SELECTED_CIN_ADAPLONUMBER;
    CREATE TABLE SELECTED_CIN_ADAPLONUMBER(ADAPLONUMBER VARCHAR(20), ADAPCINUMBER VARCHAR(18));

    /* STEP 5 - Loop over ADAPCI NUMBER */
    /*          Convert ADAPCI Number into LO Number */


    /*SELECT DISTINCT ADAPLONUMBER, ADAPCINUMBER into #ADAPLO from [dbo].[L_REL] JOIN #ADAPCI ON L_REL.ADAPCINUMBER = #ADAPCI.ADAPCINUMBER2;
    select * from #ADAPLO;*/

    /*DECLARE @PADAPCINUMBER VARCHAR (30)
    DECLARE ADAPCI_CURSOR CURSOR LOCAL FAST_FORWARD FOR 
            SELECT ADAPCINUMBER FROM SELECTED_ADAPCINUMBER

    OPEN ADAPCI_CURSOR
    FETCH NEXT FROM ADAPCI_CURSOR 
    INTO @PADAPCINUMBER
    
    WHILE @@FETCH_STATUS = 0
    BEGIN
        INSERT INTO #CINS
            SELECT DISTINCT REPLACE(@PCIN,'/','-') 
            FROM #CINS_TEMP

        FETCH NEXT FROM CINS_CURSOR 
            INTO @PCIN
    END*/
    /*into #ADAPLO*/

    /*INSERT INTO SELECTED_CIN_ADAPLONUMBER*/

    /*INSERT INTO SELECTED_CIN_ADAPLONUMBER
        SELECT DISTINCT ADAPLONUMBER, R_ADAPCI_ADAPLO.ADAPCINUMBER 
        from R_ADAPCI_ADAPLO 
        join SELECTED_ADAPCINUMBER 
        on R_ADAPCI_ADAPLO.ADAPCINUMBER = SELECTED_ADAPCINUMBER.ADAPCINUMBER;*/

    INSERT INTO SELECTED_CIN_ADAPLONUMBER
        SELECT DISTINCT ADAPLONUMBER, R_ADAPCI_ADAPLO.ADAPCINUMBER 
        from R_ADAPCI_ADAPLO 
        join SELECTED_CINS_ADAPCI 
        on R_ADAPCI_ADAPLO.ADAPCINUMBER = SELECTED_CINS_ADAPCI.ADAPCINUMBER;


GO

Step5

SELECT * from SELECTED_CIN_ADAPLONUMBER;