/* --------------- STEP 6 ----------------- */
IF OBJECT_ID ( 'dbo.Step6' ) IS NOT NULL   
    DROP PROCEDURE dbo.Step6;  
GO  
CREATE PROCEDURE dbo.Step6
WITH EXECUTE AS CALLER  
AS  

DROP TABLE IF EXISTS SELECTED_LONUMBER_EFF;
CREATE TABLE SELECTED_LONUMBER_EFF(LONUMBER_EFF VARCHAR(20));

DROP TABLE IF EXISTS SELECTED_LO_STANDARD;
CREATE TABLE SELECTED_LO_STANDARD(LONUMBER VARCHAR(20));

DROP TABLE IF EXISTS SELECTED_LO_VERSION;
CREATE TABLE SELECTED_LO_VERSION(LONUMBER VARCHAR(20));



/* --------------- STEP 6.1 --------------- */
/* Select the A_IXOFFEFF, standard selection */
DECLARE @V_MSN INTEGER = (SELECT TOP 1 MSN FROM CONFIG);
DECLARE @V_STDCODE VARCHAR(5) = (SELECT TOP 1 STANDARD FROM CONFIG);
declare @V_EFFTYPE_STANDARD VARCHAR(10)= 'STANDARD';


INSERT INTO SELECTED_LO_STANDARD
    SELECT LONUMBER from A_IXOFFEFF where EFFTYPE=@V_EFFTYPE_STANDARD AND STDCODE=@V_STDCODE 
        AND RANGE_START<= @V_MSN AND RANGE_END>=@V_MSN AND RANGE_END<>0;

/* --------------- STEP 6.2 --------------- */
/* Select the A_IXOFFEFF, version selection */
declare @V_EFFTYPE_VERSION VARCHAR(10)  = 'VERSION';
declare @V_VERSIONCODE VARCHAR(10) = (SELECT TOP 1 VERSION_ICAO FROM CONFIG)
declare @V_VERSIONRANK INTEGER = (SELECT TOP 1 VERSION_RANK FROM CONFIG)

INSERT INTO SELECTED_LO_VERSION
    SELECT LONUMBER from A_IXOFFEFF R where EFFTYPE=@V_EFFTYPE_VERSION AND VERSIONCODE=@V_VERSIONCODE
        AND RANGE_START<= @V_VERSIONRANK AND RANGE_END>=@V_VERSIONRANK AND RANGE_END<>0;


INSERT INTO SELECTED_LONUMBER_EFF  
    SELECT * FROM SELECTED_LO_STANDARD
    UNION
    SELECT * FROM SELECTED_LO_VERSION

GO

Step6 

SELECT * FROM SELECTED_LONUMBER_EFF;


