/*SELECT * FROM SELECTED_ADAPLONUMBER;
SELECT * FROM SELECTED_LONUMBER;*/


IF OBJECT_ID ( 'dbo.Step7' ) IS NOT NULL   
    DROP PROCEDURE dbo.Step7;  
GO  
CREATE PROCEDURE dbo.Step7
WITH EXECUTE AS CALLER  
AS  

DROP TABLE IF EXISTS SELECTED_FILTERED_LONUMBER;
CREATE TABLE SELECTED_FILTERED_LONUMBER(LONUMBER VARCHAR(20));


INSERT INTO SELECTED_FILTERED_LONUMBER
    SELECT DISTINCT ADAPLONUMBER as LONUMBER
    FROM SELECTED_LONUMBER_EFF join SELECTED_CIN_ADAPLONUMBER on SELECTED_CIN_ADAPLONUMBER.ADAPLONUMBER = SELECTED_LONUMBER_EFF.LONUMBER_EFF;
GO

dbo.Step7

select * from SELECTED_FILTERED_LONUMBER;