
/* For CINSTACK = 20002-J0077 */


/* step 8 - LINK LONUMBER to DSNUMBER */
/* 
Table ADAPLO - ADAPDS / R_ADAPLO_ADAPDS
Fields:
ADAPLONUMBER
ADAPLOLEGACYNUMBER
ADAPDSNUMBER
ADAPDSISSUEINDEX
CDATE
UDATE
*/

IF OBJECT_ID ( 'dbo.Step8' ) IS NOT NULL   
    DROP PROCEDURE dbo.Step8;  
GO  
CREATE PROCEDURE dbo.Step8
WITH EXECUTE AS CALLER  
AS  

DROP TABLE IF EXISTS SELECTED_REL_ADAPDS;
CREATE TABLE SELECTED_REL_ADAPDS(
    LONUMBER VARCHAR(20),
    ADAPDSNUMBER VARCHAR(20), 
    ADAPDSISSUEINDEX VARCHAR(3)
);

DROP TABLE IF EXISTS SELECTED_ADAPDS;

INSERT INTO SELECTED_REL_ADAPDS
    SELECT DISTINCT ADAPLONUMBER as LONUMBER, ADAPDSNUMBER, ADAPDSISSUEINDEX
        from R_ADAPLO_ADAPDS
        JOIN SELECTED_FILTERED_LONUMBER 
        ON R_ADAPLO_ADAPDS.ADAPLONUMBER=SELECTED_FILTERED_LONUMBER.LONUMBER;

SELECT DISTINCT O_ADAPDS.ADAPDSISSUEINDEX  
      ,ADAPDSISSUEINDEX_REL
      ,O_ADAPDS.ADAPDSNUMBER
      ,[BESTMATURITYWEIGHT]
      ,[BOUGHTOUTINDICATOR]
      ,[CANCELLATION]
      ,[CDATE]
      ,[COMMENTS]
      ,[CONSUMEROFTHEELEMENTCODE]
      ,[CREATETIMESTAMP]
      ,[DEFEXPLOITATIONRESPONSIBLE]
      ,[DESIGNSTATUS]
      ,[DOMESTICTITLE]
      ,[EFFECTIVEDATE]
      ,[ENGLISHTITLE]
      ,[GENERALCODE]
      ,[GENERICVERSIONITERATION]
      ,[GEOGRAPHICALID]
      ,[ICYNUMBER]
      ,[ICYREFERENCE]
      ,[IDENTIFIABLEPART]
      ,[IDENTNUMBER]
      ,[INTERCHANGEABILITYCODE]
      ,[IS_LAST_ISSUE]
      ,[IS_REL_ISSUE]
      ,[ITEMNUMBER]
      ,[ITEMZONE]
      ,[LOCATION]
      ,[LOCK]
      ,[LOCKINGRESPONSIBLE]
      ,[LOGISTICCODE]
      ,[LOGISTICCODEIMPORTED]
      ,[MANUFACTURINGCODE]
      ,[MANUFACTURINGINDEX]
      ,[MANUFACTURINGRESPONSIBLE]
      ,[MARKING]
      ,[MAXHEIGHT]
      ,[MOCKUP]
      ,[MODIFYTIMESTAMP]
      ,[MORPHODIMENSIONALCODE]
      ,[MORPHODIMENSIONALGROUP]
      ,[NATCO]
      ,[NEEDDATE]
      ,[NEGOCIATEDNEEDDATE]
      ,[ORDINALNUMBER]
      ,[PRODUCTIONTYPE]
      ,[PROTECTIVETREATMENTCODE]
      ,[SPAREITEM]
      ,[SPECIALITYRESPONSIBLE]
      ,[STATE]
      ,[SURFACETYPE]
      ,[TEAM_DISPLAY]
      ,[TEAM_RESTRICT]
      ,[TECHNOLOGICALCODE]
      ,[UDATE]
      ,[USEDONDRAWING]
      ,[VERSIONITERATION]

    INTO SELECTED_ADAPDS

    from O_ADAPDS
    JOIN SELECTED_REL_ADAPDS 
    ON O_ADAPDS.ADAPDSISSUEINDEX=SELECTED_REL_ADAPDS.ADAPDSISSUEINDEX 
    AND O_ADAPDS.ADAPDSNUMBER=SELECTED_REL_ADAPDS.ADAPDSNUMBER;


GO

Step8

select * from SELECTED_REL_ADAPDS
select * from SELECTED_ADAPDS
