/* step 9 - LINK ADAPDS to DRWST */

IF OBJECT_ID ( 'dbo.Step9' ) IS NOT NULL   
    DROP PROCEDURE dbo.Step9;  
GO  
CREATE PROCEDURE dbo.Step9
WITH EXECUTE AS CALLER  
AS  

DROP TABLE IF EXISTS SELECTED_DRAWINGSET;
CREATE TABLE SELECTED_DRAWINGSET(
        ADAPDSNUMBER VARCHAR(20), 
        ADAPDSISSUEINDEX VARCHAR(3),
        DRAWINGSETNUMBER VARCHAR(20), 
        DRWSTISSUEINDEX VARCHAR(3)
);

INSERT INTO SELECTED_DRAWINGSET
    SELECT DISTINCT 
        SELECTED_REL_ADAPDS.ADAPDSNUMBER,
        SELECTED_REL_ADAPDS.ADAPDSISSUEINDEX,
        DRAWINGSETNUMBER, 
        DRWSTISSUEINDEX 
        
        from R_ADAPDS_DRWST 
        JOIN SELECTED_REL_ADAPDS on SELECTED_REL_ADAPDS.ADAPDSNUMBER=R_ADAPDS_DRWST.ADAPDSNUMBER AND 
                                SELECTED_REL_ADAPDS.ADAPDSISSUEINDEX=R_ADAPDS_DRWST.ADAPDSISSUEINDEX;



    DROP TABLE IF EXISTS SELECTED_DRAWINGSSET_DETAILS;
    CREATE TABLE SELECTED_DRAWINGSSET_DETAILS(
        CANCELLATIONINDEX INTEGER,
        DESIGNOFFICECODE VARCHAR(10),
        DOMESTICTITLE VARCHAR(200),
        DRAWINGSETNUMBER VARCHAR(20),
        DRWSTISSUEINDEX VARCHAR(3),
        ENGLISHTITLE VARCHAR(100),
        GEOGRAPHICALID SMALLINT,
        LOCATION VARCHAR(10),
        NATCO VARCHAR(10),
        STATUS VARCHAR(12),
        TEAM_DISPLAY VARCHAR(10),
);

INSERT INTO SELECTED_DRAWINGSSET_DETAILS
    SELECT DISTINCT
        CAST (CANCELLATIONINDEX as INT)
        ,DESIGNOFFICECODE
        ,DOMESTICTITLE
        ,O_DRWST.DRAWINGSETNUMBER
        ,O_DRWST.DRWSTISSUEINDEX
        ,ENGLISHTITLE
        ,GEOGRAPHICALID
        ,LOCATION
        ,NATCO
        ,STATUS
        ,TEAM_DISPLAY
    FROM O_DRWST JOIN SELECTED_DRAWINGSET 
        on SELECTED_DRAWINGSET.DRAWINGSETNUMBER=O_DRWST.DRAWINGSETNUMBER 
        AND SELECTED_DRAWINGSET.DRWSTISSUEINDEX=O_DRWST.DRWSTISSUEINDEX

GO

Step9

select * from SELECTED_DRAWINGSET;
select * from SELECTED_DRAWINGSSET_DETAILS;