/* step 9A - Select Drawings  */
/* 
TODO - ACTUALLY GET THE DRAWING DATA
SELECT R_DRWST_DRW
SELECT O_DRW


*/

IF OBJECT_ID ( 'dbo.Step9A' ) IS NOT NULL   
    DROP PROCEDURE dbo.Step9A;  
GO  
CREATE PROCEDURE dbo.Step9A
WITH EXECUTE AS CALLER  
AS  

    DROP TABLE IF EXISTS SELECTED_DRAWINGS;

    DROP TABLE IF EXISTS R_DRWST_DRW_NORM;
    SELECT 
        CAST(REVERSE( LEFT( REVERSE(R_DRWST_DRW.DRAWINGNUMBER), CHARINDEX('-', REVERSE(R_DRWST_DRW.DRAWINGNUMBER))-1 ) ) AS INT) as DRAWINGNUMBER,
        DRAWINGSETNUMBER,
        DRWISSUEINDEX,
        DRWSTISSUEINDEX
        INTO R_DRWST_DRW_NORM
        from R_DRWST_DRW
    
    SELECT DISTINCT 
       [CADTOOL]
      ,[CANCELLATIONINDEX]
      ,[CDATE]
      ,[CREATETIMESTAMP]
      ,O_DRW.[DRAWINGNUMBER]
      ,O_DRW.[DRAWINGSETNUMBER]
      ,[DRAWINGSIZE]
      ,O_DRW.[DRWISSUEINDEX]
      ,[ENGLISHTITLE]
      ,[LOCATION]
      ,[MODIFYTIMESTAMP]
      ,[NATCO]
      ,[STATUS]
      ,[TEAM_DISPLAY]
      ,[UDATE]
      ,[VERSIONITERATION]
    INTO SELECTED_DRAWINGS 
    FROM O_DRW

        JOIN R_DRWST_DRW_NORM 
            on R_DRWST_DRW_NORM.DRAWINGNUMBER=O_DRW.DRAWINGNUMBER 
        JOIN SELECTED_DRAWINGSET 
            on  SELECTED_DRAWINGSET.DRAWINGSETNUMBER=R_DRWST_DRW_NORM.DRAWINGSETNUMBER AND
                SELECTED_DRAWINGSET.DRWSTISSUEINDEX=R_DRWST_DRW_NORM.DRWSTISSUEINDEX 

GO



Step9A


select * from SELECTED_DRAWINGS;