/* step 10 -  Select DASSY */
/* 


*/

IF OBJECT_ID ( 'dbo.Step18' ) IS NOT NULL   
    DROP PROCEDURE dbo.Step18;  
GO  
CREATE PROCEDURE dbo.Step18
WITH EXECUTE AS CALLER  
AS  

DROP TABLE IF EXISTS SELECTED_ADAPDS_ADAPDS;
CREATE TABLE SELECTED_ADAPDS_ADAPDS(
        A_ADAPDSISSUEINDEX VARCHAR(3),
        A_ADAPDSNUMBER VARCHAR(20),
        ALTERNCODE VARCHAR(5),
        CDATE DATE,
        B_ADAPDSNUMBER VARCHAR(20),
        ITEMNUMBER INTEGER,
        ITEMNUMBERZONE VARCHAR(5),
        QUANTITY INTEGER,
        UDATE VARCHAR(20),
        UNIT VARCHAR(3)
);


INSERT INTO SELECTED_ADAPDS_ADAPDS
    SELECT 
        R_ADAPDS_ADAPDS.A_ADAPDSISSUEINDEX,
        R_ADAPDS_ADAPDS.A_ADAPDSNUMBER,
        ALTERNCODE,
        R_ADAPDS_ADAPDS.CDATE,
        B_ADAPDSNUMBER,
        R_ADAPDS_ADAPDS.ITEMNUMBER,
        ITEMNUMBERZONE,
        QUANTITY,
        R_ADAPDS_ADAPDS.UDATE,
        UNIT

    FROM R_ADAPDS_ADAPDS JOIN SELECTED_ADAPDS 
        on  SELECTED_ADAPDS.ADAPDSNUMBER=R_ADAPDS_ADAPDS.A_ADAPDSNUMBER AND 
            SELECTED_ADAPDS.ADAPDSISSUEINDEX=R_ADAPDS_ADAPDS.A_ADAPDSISSUEINDEX

DROP TABLE IF EXISTS SELECTED_ADAPDS2;
CREATE TABLE SELECTED_ADAPDS2(
    A_ADAPDSNUMBER VARCHAR(20), 
    A_ADAPDSISSUEINDEX VARCHAR(3),
    B_ADAPDSNUMBER VARCHAR(20), 
);


GO

Step18

select * from SELECTED_ADAPDS_ADAPDS;

